<a href="https://colab.research.google.com/github/goelanand/Tester/blob/master/Pytorch1_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTORCH VERSION 1.7.1

In [20]:
%%html
<marquee style='width: 50%; color: Red;'>Welcome to Azhar Tutorial!</marquee>


**Installing pytorch 1.7.1**

In [21]:
!pip install torch==1.7.1 

In [22]:
import torch
print('Pytorch Version: ',torch.__version__)
len(dir(torch))

Pytorch Version:  1.7.1


937

To verify our GPU capabilities, we use torch.cuda.is_available() 

In [23]:
torch.cuda.is_available()

False

SyntaxError: ignored

*check the cuda version.*

In [25]:
torch.version.cuda

'10.2'

*command we use to verify the installed version of PyTorch*

In [ ]:
!pip list pytorch

In [26]:
import torch 
import torchvision 
''' 
IF TORCHVISION pops up with some dependency issue then consider upgrading torchvision

the version of torchvision should install based on your PyTorch
torch 	torchvision	  python
1.7.1  	  0.8.2	      >=3.6
'''
#pip install --upgrade torchvision>=0.8.20
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

### **Basics of pyTorch**

In [7]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
print(x,w,b)

tensor(1., requires_grad=True) tensor(2., requires_grad=True) tensor(3., requires_grad=True)


*Build a computational graph.*

In [11]:
y = w * x + b    # y = 2 * x + 3
print(y)

tensor(5., grad_fn=<AddBackward0>)


In [12]:
# Compute gradients.
y.backward()

In [10]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(2.)


In [15]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
print(x)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

tensor([[ 0.7790,  0.0239,  1.4555],
        [ 0.7152,  0.8639, -0.1543],
        [ 0.4005, -0.5709,  0.0868],
        [-0.5331,  0.7499,  1.2245],
        [ 2.1537,  1.4167, -1.6202],
        [-2.0707,  0.0998,  0.0660],
        [ 0.3680,  2.3420,  0.8468],
        [ 0.3559,  0.5428,  2.4237],
        [-0.8717, -0.1984, -0.0118],
        [ 0.1174, -1.1647,  0.1988]])
w:  Parameter containing:
tensor([[-0.3326, -0.2945,  0.4718],
        [-0.4377,  0.0490,  0.5487]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3553, -0.5051], requires_grad=True)


In [13]:


# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[ 0.2903,  0.3816,  0.4885],
        [-0.1188, -0.0762,  0.5031]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3843, -0.0771], requires_grad=True)
loss:  1.2168896198272705
dL/dw:  tensor([[ 0.2323,  0.1272, -0.2910],
        [-0.7922, -0.0442, -0.0557]])
dL/db:  tensor([-0.2858, -0.2205])
loss after 1 step optimization:  1.2077805995941162
